title = "Cazo"
publishDir = "docs"
baseURL = "https://cazo.jp/"
languageCode = "ja-JP"
theme = "cazo"
resourceDir = "../resources"

DefaultContentLanguage = "ja"
SectionPagesMenu = "main"
Paginate = 4 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.ja]
    title = "Cazo|楮"
    weight = 1
    contentDir = "content/ja"
  [languages.en]
    title = "Cazo|楮"
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/favicon.ico"
  site_logo = "/images/icon.svg"
  description = "『Cazo』は埋もれていた、生活や社会、カルチャーまでを包括したわたしたち自身の「コンテンツ」についてのメディアです。最古のテクノロジーニュースから、気になる人物評論や小説の最前線など「過去のトレンド」を毎日発信。毎日豊富に随時アップデートしてお届けしています。"
  facebook = ""
  twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-white"
  featured_image = "/images/joshua-coleman-fXls-tVemno-unsplash.jpg"
  recent_posts_number = 4
